### ISSUE TITLE
zvážit bower, respektive robo

### ISSUE THREAD

**Issue by steinbauer** [PolywebCZ/polypress#18]
:(

**Comment by wodCZ** [comment]
https://github.com/wodCZ/sandbox/blob/master/RoboFile.php#L110-L157

https://github.com/wodCZ/sandbox/blob/master/App/Config/assets.php

**Comment by steinbauer** [comment]
@wodCZ  díky.
Na vysvětlenou: osobne me štve ta neúpriznana zavislost na npm, a boweru. Přidej composer a FBU si to na FTP prostě nenaistaluje.

Druhy směr: dát to všechno do repozitare je taky na prd, kupi se mi tam kupa bordelu uz ted a to je par kalendaru a wisiwig a zabere to vic mista nez cely projekt :(

**Comment by wodCZ** [comment]
Rozumím.
BFU bude stačit dist release (zip, jako má wordpress, zkompilované assety, šlo by taky zautomatizovat) a pro vývojáře to nebude taková otrava. npm a composer už jsou skoro povinnost a ten můj robo task ho od zbytku odprostí.

**Comment by steinbauer** [comment]
@wodCZ  Tak několik pokusů - celý jsem to rozchodil včetně zabalenim robem, ale prostě ne.... Webloaderu se nevzdám, nabízené řešení je nepraktické z několika důvodů, namátkou:
- cílená aplikace musí mít různé šablony a ty musí mít svůj vlastní předpis pro svůj web, umístěný přímo v jejich slozce, ne volany napřed z centrálního místa - takle tam dam webloader.neon do každého stylu a mám to.
- musim poustet robo při každé změně v designu, je to vysilující.


**Ale! Našel jsem toto řešení:**
- použiji [bowerphp](http://webcache.googleusercontent.com/search?q=cache:juCNRih58rYJ:bowerphp.org/+&cd=1&hl=cs&ct=clnk&gl=cz) [[git](https://github.com/Bee-Lab/bowerphp)] - prostě napsali bower v php - není třeba vůbec npm a bower => no Js :) :)
- bower install to naistaluje do vendor/asset a tam si je načte webloader
- zatím mě blbnou jen fonty, proto ještě nekomituji.

Jo je je tam nějaký limit na githum 60požadavků/hodinu, pry jde zapnout 5000/hodinu, ale zatím nevím jak.

-------------
Tak jako tak jsem rád že jsem se v tom musel začat vrtat :)

@wodCZ  Prosím, dotaz: má bower neco jako require? aby mě to zapisovalo do toho bower.json, nebo prostě musím sám?

**Comment by steinbauer** [comment]
Odpovím si sám :) :) 
![Uploading 2016-04-26 23_06_26-polypress - [D__PhpStormProjects_polypress] - ..._bower.php - PhpStorm 2016.1.png…]()

**Comment by wodCZ** [comment]
Klasicky bower ma  `bower install bootstrap --save`, jak bower.php to nevim.

**Comment by steinbauer** [comment]
@wodCZ ano, přesně tak, jen musíš ručně napsat verzi (dává tam mrzák defaultně *)...
A tu zjistíš přes phph bower.php list :)

Díky
